### PR TITLE
bump minimum php version to 5.5

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by gianarb** [comment]
This PR sounds good.. Why is it frozen?

**Comment by samsonasik** [comment]
the 2nd commit can be cherry-picked for DateTimeInterface check

**Comment by gianarb** [comment]
:+1:

**Comment by Maks3w** [comment]
You can cherry pick the commit and create a PR only with that change.

**Comment by samsonasik** [comment]
@Maks3w yes I can, but please, I create the PR before the dramatically change php require version for composer.json on all repo. I am wondering why all the change is not seeing the avaialble PR first :)

**Comment by Maks3w** [comment]
@samsonasik it's simple. you did a batch of prs without coordinate with the crteam

**Comment by gianarb** [comment]
All this words for a cherry-pick :D #25
Thanks @samsonasik for this contribution I don't know if this is a batch process but you have resolved all php5.5 compatibility and not only composer.json configuration.. Perfect!

baaahh :disappointed:

**Comment by samsonasik** [comment]
we already did get info that zf 2.5 will require php >=5.5 ... so sorry for not asking about it first to crteam.

**Comment by samsonasik** [comment]
and I check one by one the changes in every repo..., that ALL ok

**Pull request closed without merging**
