### PR TITLE
StringLength: Added length to message variables

### PR DESCRIPTION
**Pull request by FabianKoestring**
Added the ability to use `%length%` as an message variable.

I think it is better to show the user how many chars he already typed if a `min` or `max` value is set. This is optional but the ability to show the value (length) aims for a better user experience. 

**For example:**
`The input is less than %min% characters long. You already typed %length% characters.` gets converted to `The input is less than 100 characters long. You already typed 99 characters.`.

### CODE REVIEW

**Comment by vaclavvanik** [comment]
You should add test

**Comment by weierophinney** [comment]
@FabianKoestring Please ping me if/when you have added tests to validate the new behavior, and I'll schedule it for a release.

Thanks!

**Comment by FabianKoestring** [comment]
@weierophinney i added a test case. Is it ok or should i add something else?

**Comment by samsonasik** [comment]
ping @weierophinney

**Pull request closed without merging**
