### PR TITLE
`i` modifier is unused in regular expression

### PR DESCRIPTION
**Pull request by freax**
'cause there are no alpha-symbols

### CODE REVIEW

**Comment by gianarb** [comment]
Can you add a test of this case? 

Thansk!

**Comment by weierophinney** [comment]
@Maks3w Please merge to develop as well.

**Comment by Maks3w** [comment]
@weierophinney It's merged but GH seems not longer reference the commit in the PR https://github.com/zendframework/zend-validator/commit/c3fcdbbc2f65ba9a5f3dfe7e74f4e2dff40a0692

**Comment by weierophinney** [comment]
@Maks3w That's odd; as of yesterday it was still referencing the merges to develop in the PRs. Sorry for the flood of emails, then!

**Pull request merged**
