### PR TITLE
[WIP] ZF3 Start refactoring

### PR DESCRIPTION
**Pull request by bakura10**
Hi everyone :),

ping @weierophinney, @maks3w, @danizord

Here is the first attempt to refactor validator. Please read the Changelog to see the main changes I'm thinking about. If everyone is okay with that, I'll start backporting validators ! ;)

Have a nice day!

### CODE REVIEW

**Comment by Maks3w** [comment]
@bakura10 Please split the PR by changeset. It's not possible to review so much large PRs.

For example create a PR only with the result object proposal

Don't remove the validators yet add too much noise for the review.

**Comment by bakura10** [comment]
I hate working with old stuff along new stuff as I quickly get lost, that's why I actually prefer removing evertyhing. How could I create a new PR with only the changes, but deleting the old stuff?

**Comment by Maks3w** [comment]
You could create a branch starting from latest **develop** and add a commit removing only the validators and their tests.

Then you can create PRs against **your fork** and ask us for to review in your fork. When approved then cherry pick the commits and create a PR here for review.

**Comment by Maks3w** [comment]
Anyway you can start by focus in the result object proposal. Only discuss about add the class and delay the implementation across the validators for a later PR.

**Comment by Maks3w** [comment]
Again. Tiny changes makes them easy of review and quick merge.

**Comment by bakura10** [comment]
Replaced by #22

**Comment by Maks3w** [comment]
@bakura10 For avoid the deletion commit you have to create a PR against your own fork.

**Comment by bakura10** [comment]
But all the review will be made on my fork then?

I need to go right now, so let's try to catch up later ;)

Envoyé de mon iPhone

**Comment by Maks3w** [comment]
What I want (and every reviewer too) it's to have a clean commit where to put our review notes.

With a changeset of 70k lines that is not possible (browser perfomance)

**Comment by Maks3w** [comment]
@bakura10 Do it yourself, after create the PR go to the files tab and try to review your own changes.

**Comment by bakura10** [comment]
Sure I definitely understand that and my browser also hangs up when I try to open it. I was just unsure about the fact that I should do the PR against my fork, which implies that the review will need to be done on my fork. If that's not a problem then I can definitely do that ;)

Envoyé de mon iPhone

**Comment by Maks3w** [comment]
There are a lot options for do you want.

1. Remove the files but don't commit them
2. Do the removal commit but delete it before push
3. PR against your own fork so you can control the change diff

Finally see the result object as a feature (addition) and focus your mind in that task, forgive the rest of you wishlist for ZF3.

**Pull request closed without merging**
