### PR TITLE
Changes done for adding support for "ø" for DK idn

### PR DESCRIPTION
**Pull request by damanikrish**
When ever I try to create `Uri` object for url string "http://www.fitnessø.dk/", it throws an exception with message "Host "www.fitnessø.dk" is not valid or is not accepted by...". And when debugged the source, I came to know that this error is because it is not validated by HostName validator in `Uri::isValidDnsHostname()`.

### CODE REVIEW

**Comment by akrabat** [comment]
Travis failure is due to https://github.com/zendframework/zend-servicemanager/issues/182, not this PR.

**Comment by akrabat** [comment]
Are there any other characters that should be allowed in a DK url?

**Comment by damanikrish** [comment]
@akrabat , I am not sure for the other characters, I just came across the use case for this character and hence created this PR for the same.

Thanks,
Krish Damani

**Comment by damanikrish** [comment]
@akrabat , I have added two more characters and updated the PR,
Reference for allowed characters in dk domain names https://www.dk-hostmaster.dk/sites/default/files/Characters%20allowed%20in.pdf

Thanks,
Krish Damani

**Pull request merged**
